### ISSUE TITLE
LLama-3.1-70B on 2x NVIDIA L40S results in ﻿﻿torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by j-irion** [huggingface/optimum-benchmark#241]
When I try to run LLama-3.1-70B on two NVIDIA L40S it results in a torch.cuda.OutOfMemoryError. I tried simultaniously watching the VRAM usage and saw that the first L40S is getting filled up and then the error occurs. Is this expected behaviour?

This is the config I am using:
```yaml
defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: pytorch_llama

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  model: meta-llama/Meta-Llama-3.1-70B
  device: cuda
  device_ids: 0,1
  torch_dtype: float16

scenario:
  memory: true
  latency: true
  energy: true

  warmup_runs: 10
  iterations: 10
  duration: 10

  input_shapes:
    batch_size: 1
    sequence_length: 256
  generate_kwargs:
    max_new_tokens: 32
    min_new_tokens: 32
```

**Comment by IlyasMoutawwakil** [comment]
yes that's expected because you haven't specified any arguments to distribute the model. for the `pytorch` backend which is the `transfromers` implementation, you can either specify `device_map: auto` for pipeline parallelism, or `deespeed_inference: true` for tensor parallelism.

**Comment by j-irion** [comment]
Thank you! I tried it with `device_map: auto` and `deepspeed_inference: true` respectively (with both torchrun and process launcher) but the error persists. Is there anything else I could try, or is it simply not possible on this hardware?

**Comment by IlyasMoutawwakil** [comment]
You can use [model-memory-usage](https://huggingface.co/spaces/hf-accelerate/model-memory-usage) to see how much memory you'll need to load this model in fp16 (tldr: it's 260GB for a llama 70B ~ 4xA100-80GB)

**Comment by j-irion** [comment]
Thanks again! That solves my question.
